import { Timestamp, UserEntities } from '@/types'

export interface User {
  id: number
  id_str: `${number}`
  name: string
  screen_name: string
  location: string
  description: string
  url: string | null
  entities: UserEntities
  protected: boolean
  followers_count: number
  friends_count: number
  listed_count: number
  created_at: Timestamp
  favourites_count: number
  utc_offset: unknown
  time_zone: unknown
  geo_enabled: boolean
  verified: boolean
  statuses_count: number
  media_count: number
  lang: unknown
  contributors_enabled: boolean
  is_translator: boolean
  is_translation_enabled: boolean
  profile_background_color: string
  profile_background_image_url: string
  profile_background_image_url_https: string
  profile_background_tile: boolean
  profile_image_url: string
  profile_image_url_https: string
  profile_banner_url: string
  profile_image_extensions_sensitive_media_warning: unknown
  profile_image_extensions_media_availability: unknown
  profile_image_extensions_alt_text: unknown
  profile_image_extensions_media_color: object
  profile_image_extensions: object
  profile_banner_extensions_sensitive_media_warning: unknown
  profile_banner_extensions_media_availability: unknown
  profile_banner_extensions_alt_text: unknown
  profile_banner_extensions_media_color: object
  profile_banner_extensions: object
  profile_link_color: string
  profile_sidebar_border_color: string
  profile_sidebar_fill_color: string
  profile_text_color: string
  profile_use_background_image: boolean
  has_extended_profile: boolean
  default_profile: boolean
  default_profile_image: boolean
  has_custom_timelines: boolean
  can_dm: unknown
  following: unknown
  follow_request_sent: unknown
  notifications: unknown
  muting: unknown
  blocking: unknown
  blocked_by: unknown
  want_retweets: unknown
  profile_interstitial_type: string
  business_profile_state: 'none'
  translator_type: 'none'
  withheld_in_countries: unknown[]
  followed_by: unknown
  has_no_screen_name: boolean
  ext_is_blue_verified: boolean
  ext_has_nft_avatar: boolean
  ext: object
  require_some_consent: boolean
}
